name: CI/CD Pipeline Web Service
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: SSH and Deploy
              uses: appleboy/ssh-action@v1.0.0
              with:
                host: 222.124.139.228
                username: poweradmin
                password: admin@1psg
                port: 22
                script: |
                      cd /var/www/nodejs/Door-Price
                      node -v
