name: CI/CD Pipeline Web Service
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: SSH and Deploy
              uses: appleboy/ssh-action@v1.0.0
              with:
                host: ${{ secrets.SERVER_PSG_SSH_HOST }}
                username: ${{ secrets.SERVER_PSG_SSH_USERNAME }}
                password: ${{ secrets.SERVER_PSG_SSH_PWD }}
                port: ${{ secrets.SERVER_PSG_SSH_PORT }}
                script: |
                      cd ${{ secrets.SERVER_PSG_SSH_PATH }}
                      sudo npm install
